hypertrace/goagent

instrumentation/opencensus/database/hypersql/sql_test.go
instrumentation/opentelemetry/database/hypersql/sql.go
sdk/google.golang.org/grpc/attributes_test.go
sdk/google.golang.org/grpc/client.go
sdk/google.golang.org/grpc/client_test.go
sdk/google.golang.org/grpc/server.go
sdk/google.golang.org/grpc/server_test.go
sdk/internal/config/config.go
sdk/internal/mock/span.go
sdk/net/http/attributes_test.go
sdk/net/http/handler.go
sdk/net/http/handler_test.go
sdk/net/http/transport.go
sdk/net/http/transport_test.go

This PR adds support for config in GRPC and also improve test assertions to cover all attributes being added.

Adds config support for GRPC and improves test assertions

---

instrumentation/opencensus/database/hypersql/sql_test.go
instrumentation/opencensus/span.go
instrumentation/opencensus/span_test.go
instrumentation/opentelemetry/database/hypersql/sql_test.go
instrumentation/opentelemetry/span.go
instrumentation/opentelemetry/span_test.go
sdk/database/hypersql/sql.go
sdk/database/hypersql/sql_test.go
sdk/internal/mock/span.go
sdk/span.go

Somehow we weren't supporting span kind for SQL instrumentation (important for ingress/egress), hence we added support inside SDK here.
The reason why we do object config instead of functional arguments is because I think it is less *gopherish* but easier to understand, discover and read.

feat(sql): adds support for span kind.

---

.codecov.yml
codecov.yml

codecov used an old config so we are fixing it to make it possible to ignore paths.

chore(ci): fixes codecov config.

---

sdk/net/http/handler.go
sdk/net/http/handler_test.go

This PR fixes an issue with http-server instrumentation as when the body was nil we were mutating it into an empty body and that was breaking a specific condition in a user's code.

fix(http-server): fixes mutation of the request body as when nil we mutated into an empty one.

---

instrumentation/hypertrace/github.com/gorilla/hypermux/examples/server/main.go
instrumentation/hypertrace/init.go
instrumentation/opentelemetry/init.go

TraceContext propagation support isn't enabled anymore in opentelemetry libraries by default. In this repo we reenable them.
Related to https://github.com/hypertrace/goagent/pull/67

fix(opentelemetry|hypertrace): fixes opentelemetry propagation support.

---

instrumentation/opentelemetry/github.com/gorilla/hypermux/mux_test.go
sdk/net/http/contenttype.go
sdk/net/http/contenttype_go1.13.go
sdk/net/http/contenttype_go1.14.go
sdk/net/http/contenttype_go1.14_test.go
sdk/net/http/contenttype_test.go
sdk/net/http/handler_test.go

Userland code can set multiheaders directly (separated by `;`) instead of using the Header.Add API. This requires to inspect the headers using contains rather than assert equal values.
Ping @davexroth

Fix content type lookup

---

sdk/net/http/contenttype.go

This PR simplifies the content-type lookup even more.
The whole reasoning about this is that we will only support headers with canonical keys rather than accepting anything users would do by accessing directly the map.

chore: simplifies the content-type lookup even more.

---

instrumentation/opentelemetry/github.com/gorilla/hypermux/mux_test.go
sdk/net/http/attributes.go
sdk/net/http/attributes_test.go
sdk/net/http/handler_test.go
sdk/net/http/transport_test.go

better be consistent than not being consistent

always lowercase http header keys

---

sdk/net/http/contenttype.go
sdk/net/http/contenttype_test.go
sdk/net/http/handler.go
sdk/net/http/headeraccessor.go
sdk/net/http/transport.go

This will allow our ext-authz service to reuse the should-record logic.
Note envoy's protocol uses a [different format](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto#service-auth-v3-attributecontext-httprequest) for representing headers; hence, the addition of the HeaderAccessor interface.

Expose shouldRecordBodyOfContentType for use by other packages

---

sdk/net/http/attributes.go
sdk/net/http/headeraccessor.go

Allows other packages to reuse the logic for setting header attributes. (Will be used by an authz service).

Expose SetAttributesFromHeaders

---

instrumentation/hypertrace/init.go

chore(hypertrace): reuse opentelemetry Init in hypertrace package.

---

config/config.go
config/config_test.go

Currently there is no way to load env and defaults from an existing config object and we need that when the config does not come from a config file.

feat(config): adds load from env functionality to config.

---

config/README.md
config/cmd/generator/main.go
config/config.go
config/config.pbloader.go
config/config_test.go

If the propagation formats were defined in the config file, there were getting overwritten by the default value.

configured propagation formats ignored

---

go.mod
go.sum
instrumentation/hypertrace/init.go
instrumentation/opentelemetry/database/hypersql/sql_test.go
instrumentation/opentelemetry/init.go
instrumentation/opentelemetry/init_test.go
instrumentation/opentelemetry/span.go
sdk/config/config.go

Added InitService which internally creates a new TracerProvider
used for creating services with a different set of resource attributes
then the default service.

feat: Add support for multiple tracer providers

---

sdk/instrumentation/net/http/transport.go
sdk/instrumentation/net/http/transport_test.go

This PR fixes the case there the request body is `nil` as we were trying to read it without such check.
Ping @samarth-gupta-traceable

fix: fixes request body handling for it to be nil in transport.

---

sdk/instrumentation/net/http/handler.go
sdk/instrumentation/net/http/handler_test.go

The go http package copies the http host header to `request.Host` field and deletes the header from the map.
This change allows us to record the http host.
https://github.com/golang/go/blob/ab4085ce84f8378b4ec2dfdbbc44c98cb92debe5/src/net/http/request.go#L154-L155
The above behavior prevents `SetAttributesFromHeaders` method from being able to record the host header.
The new test asserts that `request.Host` is added to the spans attributes.

fix: Update http handler to record host

---

instrumentation/hypertrace/google.golang.org/hypergrpc/examples/helloworld/helloworldv1.pb.go
sdk/instrumentation/google.golang.org/grpc/serializer.go
sdk/instrumentation/google.golang.org/grpc/serializer_test.go

Applications that use an older protobuf format previously would not have their body captured. 
We need to use the `github.com/golang/protobuf/proto` proto instead because the conversion methods(`MessageV2`) are not available in the `google.golang.org/protobuf/proto`
New test asserts we can capture v1 & v2 protobuf spans(v2 is what was previously present in the hello world sample app)
Ensured the sample app still reports body data, and tested a v1 protobuf application locally and it is now reporting that data.

Report v1 proto data

---

instrumentation/hypertrace/google.golang.org/hypergrpc/examples/helloworld/helloworldv1.pb.go
sdk/instrumentation/google.golang.org/grpc/serializer.go
sdk/instrumentation/google.golang.org/grpc/serializer_test.go
sdk/instrumentation/google.golang.org/grpc/server.go
sdk/instrumentation/google.golang.org/grpc/server_test.go

:method & :scheme are not reported - these fields are not present in the `metadata.FromIncomingContext(ctx)` metadata map.
method - grpc will error if a request is received that doesn't use POST, and the grpc spec defines post as the only valid http method, just apply a default for this attribute
scheme - peer.AuthInfo will be nil if no transport security is configured
Edits to existing/new test cases for these attributes

fix: Always report rpc method & scheme

---

instrumentation/opentelemetry/database/hypersql/sql_test.go
instrumentation/opentelemetry/github.com/gin-gonic/hypergin/gin_test.go
instrumentation/opentelemetry/github.com/gorilla/hypermux/mux_test.go
instrumentation/opentelemetry/github.com/jackc/hyperpgx/integrationtest/integration_test.go
instrumentation/opentelemetry/google.golang.org/hypergrpc/client_test.go
instrumentation/opentelemetry/google.golang.org/hypergrpc/server_test.go
instrumentation/opentelemetry/internal/tracetesting/recorder.go
instrumentation/opentelemetry/internal/tracetesting/spanattributes.go
instrumentation/opentelemetry/internal/tracetesting/spanattributes_test.go
instrumentation/opentelemetry/internal/tracetesting/tracing.go
instrumentation/opentelemetry/net/hyperhttp/handler_test.go
instrumentation/opentelemetry/net/hyperhttp/transport_test.go

This PR changes the internal package containing testing utils for tracing into a tracetesting package. This to make it explicit the testing purposes but also to organize the packages under internal.

chore: relocate internal package used for testing.

---

.github/workflows/pr-test.yml
instrumentation/opentelemetry/init.go

It was required for zipkin exporter but not anymore, see https://github.com/open-telemetry/opentelemetry-go/pull/1697.

chore: removes service name as parameter for exporter

---

instrumentation/opencensus/span.go
instrumentation/opentelemetry/span.go
sdk/codes.go
sdk/internal/mock/span.go
sdk/span.go

This PR adds support for status API in spans, allowing users to set the status of an operation despite the error value.

feat: adds span status support.

---

instrumentation/opencensus/span.go
instrumentation/opencensus/span_test.go
instrumentation/opentelemetry/github.com/jackc/hyperpgx/pgx.go
instrumentation/opentelemetry/span.go
instrumentation/opentelemetry/span_test.go
sdk/instrumentation/database/sql/sql.go
sdk/instrumentation/database/sql/sql_test.go
sdk/span.go

Given https://github.com/hypertrace/goagent/pull/141 we keep consistency for kinds too.

chore: span kind keeps consistency with status codes.

---

sdk/instrumentation/database/sql/sql.go
sdk/instrumentation/database/sql/sql_test.go
sdk/internal/mock/span.go

This PR adds support for span status code in SQL instrumentation.
After Go 1-RC2 the span does include status unset by default (see https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.0.0-RC2), we need to specifically set statusOK on success and statusError otherwise.

chore: adds span status to SQL instrumentation.

---

sdk/instrumentation/net/http/contenttype.go
sdk/instrumentation/net/http/contenttype_test.go

To match other agents, we match on the "stem" of the content-type instead of the full name so we can cover all possible cases. eg. for `application/json` we use `json` so we can capture `application/vnd.api+json` as well.
Unit tests

match on content-type header "stems" instead of full header strings

---

config/defaults.go
examples/gin-server/go.mod
examples/gin-server/go.sum
examples/mux-server/go.sum
examples/postgres-query/go.sum
examples/sql-query/go.sum
go.mod
go.sum
instrumentation/hypertrace/github.com/jackc/hyperpgx/go.sum
instrumentation/opentelemetry/github.com/jackc/hyperpgx/go.sum
instrumentation/opentelemetry/net/hyperhttp/handler_test.go
sdk/instrumentation/google.golang.org/grpc/server.go
sdk/instrumentation/google.golang.org/grpc/server_test.go
sdk/instrumentation/net/http/handler.go
sdk/instrumentation/net/http/handler_test.go

Capture all bytes up to `max_processing_size` (1mb default) in memory and pass that through the blocking code.  Any data after `max_processing_size` should not be captured.  Only the value of `body_max_size_bytes` (128K default) should be added to the span attribute.

feat: adds support for body max processing size in bytes

---

examples/sql-query/go.mod
examples/sql-query/go.sum
examples/sql-query/main.go

More comprehensive mysql example with an http-server before the db. The point is to pass down the context and invoke `ExecContext` instead `Exec` when making the db calls so that they can be correlated to the server calls.

chore: more comprehensive mysql example with an http-server before the db

---

instrumentation/opentelemetry/init.go
instrumentation/opentelemetry/init_test.go

The wrapper wraps over OnStart and OnEnd calls and is responsible
to delegate calls to the wrapped otel span processor

feat: add ability to specify wrapper over opentelemetry span processor

---

instrumentation/hypertrace/google.golang.org/hypergrpc/client.go
instrumentation/hypertrace/google.golang.org/hypergrpc/server.go
instrumentation/hypertrace/init.go
instrumentation/opentelemetry/google.golang.org/hypergrpc/client.go
instrumentation/opentelemetry/google.golang.org/hypergrpc/server.go
instrumentation/opentelemetry/init.go
instrumentation/opentelemetry/init_test.go
sdk/instrumentation/google.golang.org/grpc/client.go
sdk/instrumentation/google.golang.org/grpc/client_test.go
sdk/instrumentation/google.golang.org/grpc/server.go
sdk/instrumentation/google.golang.org/grpc/server_test.go

RegisterService returns the TracerProvider created when a service is registered so that it can be passed onto config options of consumers who use otel instrumentation eg. otelgrpc. Also the grpc instrumentation can also take in a map of attributes to be added to every span.
Manual tests

feat: modify RegisterService api to return the TracerProvider as well

---

examples/http-server/main.go
instrumentation/hypertrace/net/hyperhttp/handler.go
instrumentation/hypertrace/net/hyperhttp/transport.go
instrumentation/opencensus/net/hyperhttp/handler.go
instrumentation/opencensus/net/hyperhttp/transport.go
instrumentation/opentelemetry/github.com/gin-gonic/hypergin/gin.go
instrumentation/opentelemetry/github.com/gorilla/hypermux/mux.go
instrumentation/opentelemetry/net/hyperhttp/handler.go
instrumentation/opentelemetry/net/hyperhttp/transport.go
sdk/instrumentation/net/http/handler.go
sdk/instrumentation/net/http/handler_test.go
sdk/instrumentation/net/http/transport.go
sdk/instrumentation/net/http/transport_test.go

Modify the API to pass a map of strings as attributes to be added to the spans created during net/http instrumentation.
Unit tests. Will run the example and verify the additional span attributes appear in the spans.

feat: provide api to pass additional span attributes to http instrumentation

---

examples/http-server/main.go
sdk/filter/filter.go
sdk/filter/multifilter.go
sdk/filter/multifilter_test.go
sdk/filter/noop.go
sdk/filter/noop_test.go
sdk/internal/mock/filter.go

This PR adds a new Filter interface that is a combination of EvaluateURLAndHeaders and EvaluateBody. The motivation is performance if we do not need two calls. 
Added/updated the unit tests.

feat: Add filter interface Evaluate()

---

sdk/instrumentation/google.golang.org/grpc/client.go
sdk/instrumentation/google.golang.org/grpc/client_test.go

Large GRPC client request and response bodies were not being truncated. GRPC server instrumentation truncates them though.
Unit tests and local tests

fix: grpc client large bodies truncation

---

sdk/instrumentation/bodyattribute/bodyattribute.go
sdk/instrumentation/bodyattribute/bodyattribute_test.go
sdk/instrumentation/net/http/body.go
sdk/instrumentation/net/http/body_test.go
sdk/instrumentation/net/http/contenttype.go
sdk/instrumentation/net/http/contenttype_test.go
sdk/instrumentation/net/http/handler.go
sdk/instrumentation/net/http/handler_test.go
sdk/instrumentation/net/http/transport.go
sdk/instrumentation/net/http/transport_test.go

Support capturing multipart/form-data request and response body. Note that we are base64 encoding these types of bodies since they may contain non utf8 bytes which would break the exporters.
Added unit tests and verified locally using an example
- [✅  ] I have added tests that prove my fix is effective or that my feature works
- [✅  ] Any dependent changes have been merged and published in downstream modules

feat: multipart/form-data data capture support

---

version/version.go

The version string should not have been updated to exclude the `-dev` portion of the string

Version should include -dev

---

go.mod
go.sum
instrumentation/opentelemetry/init_test.go
instrumentation/opentelemetry/internal/identifier/identifier.go
instrumentation/opentelemetry/span.go
instrumentation/opentelemetry/span_test.go

This adds a `service.instance.id` to every span.  
I tried adding this as a processor; however that didn't seem to work with our `InitWithSpanProcessorWrapper` I also tried adding it as a starting attribute using `trace.WithAttributes` however; those are filtered out during sampling.
Instead we just add it to each span during startSpan. If we'd prefer a different approach happy to revisit.(this seems like the most minimally invasive approach i think)
From docs about this attribute: 
> [3]: MUST be unique for each instance of the same service.namespace,service.name pair (in other words service.namespace,service.name,service.instance.id triplet MUST be globally unique). The ID helps to distinguish instances of the same service that exist at the same time (e.g. instances of a horizontally …

Add "service.instance.id" to every span

---

instrumentation/hypertrace/metrics.go
instrumentation/hypertrace/net/hyperhttp/handler.go
instrumentation/opencensus/metrics.go
instrumentation/opencensus/net/hyperhttp/handler.go
instrumentation/opentelemetry/github.com/gin-gonic/hypergin/gin.go
instrumentation/opentelemetry/github.com/gorilla/hypermux/mux.go
instrumentation/opentelemetry/init.go
instrumentation/opentelemetry/metrics.go
instrumentation/opentelemetry/net/hyperhttp/handler.go
sdk/instrumentation/net/http/handler.go
sdk/instrumentation/net/http/handler_test.go
sdk/metrics.go

This is to be able to send the correct operation name from the various frameworks including gorilla mux. Also, remove the otel metrics specific code from the sdk.
- Tested locally
- [✅  ] Any dependent changes have been merged and published in downstream modules

feat: refactor http operation metrics to handle multiple frameworks

---

instrumentation/opentelemetry/init.go
instrumentation/opentelemetry/init_test.go

This is because we use the traces OTLP endpoint for metrics if the metrics endpoint is not set. By default the trace endpoint is zipkin which does not have support for metrics.
Added unit tests and tested locally.
- [✅  ] I have added tests that prove my fix is effective or that my feature works
- [ ✅ ] Any dependent changes have been merged and published in downstream modules

fix: disable metrics if using zipkin traces endpoint but empty metrics endpoint

---

sdk/instrumentation/google.golang.org/grpc/server.go
sdk/instrumentation/google.golang.org/grpc/server_test.go
sdk/instrumentation/google.golang.org/grpc/status.go
sdk/instrumentation/google.golang.org/grpc/status_test.go

Need to map the HTTP status code returned by the filter logic to GRPC status code for GRPC instrumentation.
Unit tests.
- [✅  ] Any dependent changes have been merged and published in downstream modules

fix: map HTTP response status code to equivalent GRPC Status code

---

instrumentation/opentelemetry/metrics.go

Fixing a crash caused by concurrent read and write of map
```
fatal error: concurrent map read and map write
goroutine 53 [running]:
runtime.throw({0xc1255c?, 0xb66080?})
/usr/lib/go-1.18/src/runtime/panic.go:992 +0x71 fp=0xc0000bd018 sp=0xc0000bcfe8 pc=0x43aa31
runtime.mapaccess1_faststr(0xb66080?, 0xc000ddb540?, {0xc15193, 0x24})
/usr/lib/go-1.18/src/runtime/map_faststr.go:22 +0x3a5 fp=0xc0000bd080 sp=0xc0000bd018 pc=0x416265
github.com/hypertrace/goagent/instrumentation/opentelemetry.(*HttpOperationMetricsHandler).AddToRequestCount(0xc0001266d0, 0xc000659f20?, 0xc000ad4f00)
/root/go/pkg/mod/github.com/hypertrace/goagent@v0.13.0/instrumentation/opentelemetry/metrics.go:56 +0x1d8 fp=0xc0000bd138 sp=0xc0000bd080 pc=0x9fd9b8
github.com/hypertrace/goagent/sdk/instrumentation/net/http.(*handl …
```

fix: use a rwlock to avoid concurrent map read and write

---

instrumentation/opencensus/metrics.go
instrumentation/opentelemetry/batchspanprocessor/batch_span_processor.modified.go
instrumentation/opentelemetry/metrics.go
sdk/instrumentation/net/http/handler.go
sdk/instrumentation/net/http/handler_test.go
sdk/metrics.go

Switch to struct fields. No need to use a map for static fields

fix: remove metric maps

---

instrumentation/opentelemetry/init.go
instrumentation/opentelemetry/init_additional.go
instrumentation/opentelemetry/init_test.go

This will make it easier for consumers of this module to pass their own agent names and versions.
Unit tests and tested locally

chore: make it easier to pass resource agent name and version

---

instrumentation/opentelemetry/span.go
instrumentation/opentelemetry/span_test.go
sdk/internal/mock/span.go
sdk/span.go

Adding a generic GetAll method for attributes so that all the attributes can be queried at once

 adding generic attributes interface 

---

sdk/instrumentation/bodyattribute/bodyattribute.go
sdk/instrumentation/bodyattribute/bodyattribute_test.go

This PR adds functions to set bodies in span in case bodies are already truncated.
Currently for body attributes `SetTruncatedBodyAttribute` and `SetTruncatedEncodedBodyAttribute` functions are supported, but to use those users will need to read complete body and then let these functions do the truncation.
to support reading limited sized bodies, new functions are added which truncated attribute.
Will be updating unit tests.

ENG-37132: Adding bodyAttribute functions to support already truncated bodies

---

instrumentation/opentelemetry/span.go
instrumentation/opentelemetry/span_test.go
sdk/internal/mock/span.go
sdk/span.go

Adding an iterator interface on AttributeList so that the iterator can be queried without creating an additional slice. 
Continuation of this pr: https://github.com/hypertrace/goagent/pull/217
ref: https://github.com/hypertrace/goagent/pull/217/files#r1385540220

adding iterator interface and removing GetAll() method from attribute list

---

sdk/filter/filter.go
sdk/filter/multifilter.go
sdk/filter/multifilter_test.go
sdk/filter/noop.go
sdk/filter/noop_test.go
sdk/instrumentation/google.golang.org/grpc/server.go
sdk/instrumentation/google.golang.org/grpc/server_test.go
sdk/instrumentation/net/http/handler.go
sdk/instrumentation/net/http/handler_test.go
sdk/internal/mock/filter.go

Updating the filter interface to have only a single method, `Evaluate`. And when calling evaluate, all the relevant attributes/headers are expected to be present as part of the span

feat: update filter interface to process only based on spans

---

instrumentation/opentelemetry/span.go
instrumentation/opentelemetry/span_test.go
sdk/instrumentation/net/http/handler.go
sdk/instrumentation/net/http/handler_test.go
sdk/internal/mock/span.go
sdk/span.go

1. adding a length method to attribute list
2. Updating the http.url attribute in net/http instrumentation in case if its not the complete url

feat: adding length method to attribute list and updating http.url attribute in net/http instrumentation

---

instrumentation/opentelemetry/batchspanprocessor/batch_span_processor.modified.go
instrumentation/opentelemetry/batchspanprocessor/batch_span_processor_modified_test.go

Sometimes the exporter panics leading the agent to crash. This change will recover from the panic.
Panic stacktrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4742d0]
goroutine 198 [running]:
google.golang.org/protobuf/encoding/protowire.AppendString(...)
/root/go/pkg/mod/google.golang.org/protobuf@v1.31.0/encoding/protowire/wire.go:455
google.golang.org/protobuf/internal/impl.appendStringValidateUTF8({0xc00853a000?, 0x413d64?, 0xc002ecb058?}, {0x16?}, 0xc002ecb070?, {0x6b?})
/root/go/pkg/mod/google.golang.org/protobuf@v1.31.0/internal/impl/codec_gen.go:4958 +0x95
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOneofFieldCoders.func4({0xc00853a000, 0x291, 0xb49}, {0x413d64?}, …
```

fix: recover from exporter panic in our custom batch_span_processor

---

go.mod
go.sum
instrumentation/opentelemetry/init.go
instrumentation/opentelemetry/internal/metrics/system_metrics.go

Adding CPU and Memory monitoring metrics
deployed and tested locally. 

adding cpu and memory metrics

---

sdk/filter/result/filter_result.go
sdk/instrumentation/google.golang.org/grpc/common_test.go
sdk/instrumentation/google.golang.org/grpc/server.go
sdk/instrumentation/google.golang.org/grpc/server_test.go
sdk/instrumentation/net/http/attributes_test.go
sdk/instrumentation/net/http/contenttype_test.go
sdk/instrumentation/net/http/handler.go
sdk/instrumentation/net/http/handler_test.go
sdk/instrumentation/net/http/headeraccessor.go
sdk/instrumentation/net/http/transport.go

Adding a Decoration field to FilterResult. The Decoration struct can have mutations defined on request or response objects which should be applied on a filter result match. Starting with request header injections, in which a list of headers can be specified to be injected on a filter evaluation match

feat: updating filter result to add decorations

---

instrumentation/opentelemetry/span.go
instrumentation/opentelemetry/span_test.go
sdk/internal/mock/span.go
sdk/span.go

Added a way to directly get the spanId, from the span that is created.

feat: Update span interface to add a new function which will return span id

---

instrumentation/opentelemetry/init.go

Need to allow Headers to be specified for metrics export as well.

ENG-58885 add ServiceOption support to metrics

---

examples/gin-server/main.go
examples/grpc-client/main.go
examples/grpc-server/main.go
examples/http-server/main.go
examples/mux-server/main.go
examples/sql-query/main.go
sdk/instrumentation/net/http/attributes.go

Some more instrumentation examples

ENGTAI-24429: Add more examples and fix gosec issues

---

instrumentation/opentelemetry/init.go
instrumentation/opentelemetry/init_test.go

Originally I tried implementing this by storing a single global exporter and then each new registered service tracer would have it's own in memory exporter. This performed essentially the same(marginal benefit ~1% in benchmarks..)
As an alternative, otel exposes a `WithGRPCConn` argument we can pass to each exporter. This keeps our implementation simpler and achieves essentially the same result. 
Since we need to have a reference to the shared connection the flow would be: 
```
// Create the config before calling 1 of the .Init functions
grpcConn, err := hypertrace.CreateGrpcConn(agentCfg)
// we need to handle closing the Conn, the underlying TraceProviders will not shut it down since they don't "own" the connection
defer grpcConn.Close()
flusher, err := …
```

ENGTAI-64543: expose withGrpcConn to allow exporters to share connection
