hypertrace/goagent

instrumentation/opentelemetry/database/hypersql/sql.go, instrumentation/opentelemetry/database/hypersql/sql_test.go
This PR adds standard attributes support to SQL tracing and as first attributes includes `db.system` attributes.
Ping @davexroth
=> feat(sql): adds standard attributes to SQL instrumentation.

instrumentation/opentelemetry/database/hypersql/dsn.go, instrumentation/opentelemetry/database/hypersql/dsn_test.go, instrumentation/opentelemetry/database/hypersql/sql.go
This PR adds support for parsing the DSN and obtain attributes out of them.
=> Adds standard tags

README.md, go.mod, go.sum, instrumentation/hypertrace/github.com/gorilla/hypermux/examples/server/main.go, instrumentation/hypertrace/github.com/gorilla/hypermux/mux.go, instrumentation/opentelemetry/github.com/gorilla/hypermux/RATIONALE.md, instrumentation/opentelemetry/github.com/gorilla/hypermux/mux.go, instrumentation/opentelemetry/github.com/gorilla/hypermux/mux_test.go
This PR adds support for `gorilla/mux`.
TODO: verify body/headers and being recorded as expected.
=> feat(gorilla/mux): adds support for gorilla/mux.

README.md, config/README.md
This PR improves documentation around config.
=> docs: improves documentation for config.

instrumentation/opentelemetry/init.go, instrumentation/opentelemetry/init_test.go
Fixes #79 
Need for integration with Ambassador
=> Support b3

instrumentation/opencensus/database/hypersql/sql.go, instrumentation/opentelemetry/database/hypersql/sql.go, instrumentation/opentelemetry/domain.go, sdk/database/sql/dsn.go, sdk/database/sql/dsn_test.go, sdk/database/sql/sql.go, sdk/database/sql/sql_test.go
This PR changes the SDK SQL package to be coherent with the other packages inside SDK.
=> chore: renames SQL sdk package.

README.md, instrumentation/hypertrace/database/hypersql/README.md
This PR adds documentation for the hypersql package.
Ping @nxvl
=> docs(hypersql): this PR adds documentation for the hypersql package.

instrumentation/hypertrace/propagation/propagation.go, instrumentation/hypertrace/span.go, instrumentation/opentelemetry/span.go, sdk/net/http/attributes.go, sdk/net/http/attributes_test.go, sdk/net/http/contenttype.go, sdk/net/http/handler.go, sdk/net/http/headeraccessor.go, sdk/net/http/headeraccessor_test.go, sdk/net/http/transport.go, sdk/span.go
This PR:
- adds support for propagation in hypertrace package
- improves header accessor API
- adds StartSpan function to hypertrace
=> Improves header accessor

Makefile
=> chore(config): fixes proto version in the code generation for config.

README.md, instrumentation/opentelemetry/init_test.go, instrumentation/opentelemetry/net/hyperhttp/transport_test.go, sdk/filter/README.md, sdk/filter/filter.go, sdk/filter/filter_test.go, sdk/instrumentation/google.golang.org/grpc/server.go, sdk/instrumentation/google.golang.org/grpc/server_test.go, sdk/instrumentation/net/http/handler.go, sdk/instrumentation/net/http/handler_test.go, sdk/internal/mock/filter.go
motivation and context in https://github.com/hypertrace/goagent/pull/105#issuecomment-801627631
Ping @ryanericson @davexroth
=> breaking: changes the filter interface to remove individual headers and url methods.

instrumentation/opentelemetry/init.go
This PR improves the logic for resolving the exporter.
=> chore: improves exporters logic.

README.md
=> added link to the 'yet another go agent' blog post

instrumentation/opentelemetry/init.go
Adding hypertrace resource attributes, and updating telemetry attributes
=> Add resource attributes

config/defaults.go
Revert defaulting to OTLP exporter
=> Default to zipkin exporter

.github/workflows/pr-test.yml
Adds snyk monitoring and testing to the goagent repository to alert us when our dependencies are known to be insecure and prevent us from adding vulnerable dependencies by mistake. 
N/A, the only thing this change does is add security test coverage
N/A
=> 🔒  add security scanning to pr step

instrumentation/opentelemetry/init.go, instrumentation/opentelemetry/init_test.go
Addresses https://github.com/hypertrace/pythonagent/pull/198#issuecomment-834194923
=> chore(OTLP): fixes OTLP exporter endpoint by trimming off the protocol

config/defaults.go, sdk/instrumentation/google.golang.org/grpc/body.go, sdk/instrumentation/google.golang.org/grpc/body_test.go, sdk/instrumentation/google.golang.org/grpc/server.go, sdk/instrumentation/net/http/body.go, sdk/instrumentation/net/http/body_test.go, sdk/instrumentation/net/http/handler.go, sdk/instrumentation/net/http/handler_test.go, sdk/instrumentation/net/http/transport.go, sdk/instrumentation/net/http/transport_test.go
This PR adds support for max body size on body capture.
Ping @davexroth
=> feat(http/rpc): adds support for max body size.

README.md
=> docs: fixes docs for filters.

README.md
=> chore: fixes examples for gin

examples/gin-server/go.sum, examples/mux-server/go.sum, examples/postgres-query/go.sum, examples/sql-query/go.sum, go.mod, go.sum, instrumentation/hypertrace/github.com/jackc/hyperpgx/go.sum, instrumentation/opentelemetry/github.com/jackc/hyperpgx/go.sum
Follows from https://github.com/hypertrace/agent-config/pull/71
=> chore: allows to unmarshal fields with unknown fields.

go.sum, instrumentation/hypertrace/github.com/gorilla/hypermux/mux.go, instrumentation/hypertrace/github.com/gorilla/hypermux/options.go, instrumentation/hypertrace/github.com/gorilla/hypermux/options_test.go, instrumentation/hypertrace/github.com/jackc/hyperpgx/go.sum, instrumentation/opentelemetry/github.com/jackc/hyperpgx/go.sum
This adds support for mux options instead of SDK.
=> chore: adds options for mux middleware.

examples/gin-server/main.go, instrumentation/hypertrace/github.com/gin-gonic/hypergin/gin.go, instrumentation/hypertrace/github.com/gin-gonic/hypergin/gin_test.go, instrumentation/hypertrace/github.com/gin-gonic/hypergin/options.go, instrumentation/hypertrace/github.com/gin-gonic/hypergin/options_test.go
This PR alings the options API for gin instrumentation.
=> feat: adds options for gin middleware.

config/defaults.go, instrumentation/opentelemetry/init.go, instrumentation/opentelemetry/init_test.go, instrumentation/opentelemetry/span_test.go, sdk/config/config.go, sdk/internal/config/config.go
This PR adds support for enabling/disabling the agent through the config.
=> feat: adds support for enabling disabling tracing in the agent.

README.md, examples/manual/main.go, instrumentation/opencensus/span.go, instrumentation/opencensus/span_test.go, instrumentation/opentelemetry/span.go, instrumentation/opentelemetry/span_test.go, sdk/internal/mock/span.go, sdk/span.go
AddEvent to Span sdk api. The function takes in a name, timestamp and attributes for the event.
Unit tests and also tested locally
=> feat: AddEvent api

instrumentation/opentelemetry/github.com/gin-gonic/hypergin/gin_test.go
Fixing an unstable unit test. github.com/hypertrace/goagent/instrumentation/opentelemetry/github.com/gin-gonic/hypergin.TestTraceContextIsPropagate
- [✅  ] I have added tests that prove my fix is effective or that my feature works
=> fix: unstable unit test. open arbitrary ports instead of hardcoded ones

examples/http-server/main.go
Add an example outgoing http call
=> Add example outgoing call handler

.github/workflows/pr-test.yml
Lint failures after otel update(again didn't appear on feature branch 🤔) - bumping this to see if they resolve, they appear resolved again here & locally.
=> Bump golangci linter

.github/workflows/pr-test.yml
=> Update golangci lint - add verbose logging

config/defaults.go
Added default for remote.enable_grpc_loadbalancing
=> Client loadbalance default value

.github/workflows/static-analysis.yml
adding GoSec scan for goagent repo
=> adding gosec scan for goagent repo

instrumentation/opentelemetry/init.go, instrumentation/opentelemetry/init_test.go, sdk/filter/README.md
Important to indicate when an instrumented app starts up
Tested locally using an instrumented app.
=> feat: create a startup span in init

.github/CODEOWNERS, .github/workflows/pr-test.yml, instrumentation/opencensus/init.go, instrumentation/opentelemetry/init.go, instrumentation/opentelemetry/init_additional.go
update github action versions and fix some gosec issues
Unit tests still passing
=> chore: update github action versions and fix some gosec issues

sdk/filter/result/filter_result.go
Add filter.ResponseMessage field.
=> add ResponseMessage field to FilterResult
